version: '3.8'
services:
  php-apache:
    image: php-apache_im
    build:
      context: .
      dockerfile: ./lib/docker/php-apache/Dockerfile
    platform: linux/amd64
    container_name: php-apache_im
    ports:
      - "9080:80"
    volumes:
      - ./src:/var/www/html/src
    restart: always
    depends_on:
      - db
  db:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    volumes:
      - type: bind
        source: ./lib/docker/mysql/initdb/sample_schema_mysql.sql
        target: /docker-entrypoint-initdb.d/sample_schema_mysql.sql
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: im4135dev
      MYSQL_USER: web
      MYSQL_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
#    ports:
#      - 127.0.0.1:3306:3306
